<?php
/** One-time web installer. Disabled automatically once config.php exists. */
final class InstallController
{
    private function guard(): void
    {
        if (INSTALLED) throw new HttpException(t('error.404'), 404);
    }

    public function form(): void
    {
        $this->guard();
        $checks = [
            'PHP 8.1+' => version_compare(PHP_VERSION, '8.1', '>='),
            'PDO MySQL' => extension_loaded('pdo_mysql'),
            'GD (images)' => extension_loaded('gd'),
            'OpenSSL' => extension_loaded('openssl'),
            'cURL' => extension_loaded('curl'),
            'mbstring' => extension_loaded('mbstring'),
            'fileinfo' => extension_loaded('fileinfo'),
            'app/config writable' => is_writable(APP . '/config'),
            'storage writable' => is_writable(STORAGE),
            'assets/uploads writable' => is_writable(PUBLIC_UPLOADS),
        ];
        header('Content-Type: text/html; charset=utf-8');
        echo View::render('pages/install', ['checks' => $checks]);
    }

    public function run(): void
    {
        $this->guard();
        $host = input('db_host') ?: 'localhost';
        $port = input_int('db_port', 3306);
        $name = input('db_name'); $user = input('db_user'); $pass = (string)($_POST['db_pass'] ?? '');
        $errors = [];
        if (!preg_match('/^[A-Za-z0-9_\-\$]+$/', (string)$name)) $errors['db_name'] = 'Database name is required.';
        if ($user === '') $errors['db_user'] = 'Database user is required.';
        $adminEmail = mb_strtolower((string)input('admin_email'));
        $adminPass = (string)($_POST['admin_password'] ?? '');
        if ($adminEmail !== '') {
            if (!filter_var($adminEmail, FILTER_VALIDATE_EMAIL)) $errors['admin_email'] = 'Valid email required.';
            if (($pe = Auth::validatePassword($adminPass)) !== null) $errors['admin_password'] = $pe;
            if (input('admin_name') === '') $errors['admin_name'] = 'Name required.';
        }
        if ($errors) json_out(['ok' => false, 'message' => 'Please fix the highlighted fields.', 'errors' => $errors], 422);

        try {
            $pdo = DB::connect($host, $port, $name, $user, $pass);
        } catch (PDOException $e) {
            json_out(['ok' => false, 'message' => 'Database connection failed: ' . $e->getMessage()], 422);
        }

        $sql = (string)file_get_contents(ROOT . '/database/schema.sql');
        $sql = preg_replace('/^--.*$/m', '', $sql);
        foreach (array_filter(array_map('trim', explode(";\n", $sql))) as $stmt) {
            try { $pdo->exec($stmt); }
            catch (PDOException $e) {
                // Views are convenience only; some shared hosts deny CREATE VIEW.
                if (stripos($stmt, 'CREATE OR REPLACE VIEW') === 0) continue;
                json_out(['ok' => false, 'message' => 'Schema error: ' . $e->getMessage()], 500);
            }
        }

        $config = [
            'db' => ['host' => $host, 'port' => $port, 'name' => $name, 'user' => $user, 'pass' => $pass],
            'app_key' => bin2hex(random_bytes(32)),
            'debug' => false,
            'timezone' => 'Asia/Dhaka',
        ];
        $GLOBALS['config'] = $config;
        $php = "<?php\n// Generated by the Oryzenx installer. Keep this file private.\nreturn " . var_export($config, true) . ";\n";
        if (file_put_contents(APP . '/config/config.php', $php, LOCK_EX) === false) {
            json_out(['ok' => false, 'message' => 'Could not write app/config/config.php — check permissions.'], 500);
        }
        @chmod(APP . '/config/config.php', 0640);

        // From here on, the app runs as installed.
        (require ROOT . '/database/seed.php')();
        $site = input('site_name');
        if ($site !== '') DB::q("INSERT INTO settings (setting_key, setting_value, group_name) VALUES ('site_name', ?, 'general')", [mb_substr($site, 0, 80)]);
        Settings::flush();

        if ($adminEmail !== '') {
            DB::q('INSERT INTO users (name, email, password_hash, role, email_verified_at) VALUES (?,?,?,?,NOW())
                   ON DUPLICATE KEY UPDATE role = VALUES(role), password_hash = VALUES(password_hash)',
                [mb_substr((string)input('admin_name'), 0, 100), $adminEmail, Auth::hash($adminPass), 'admin']);
        }
        try { WebPush::ensureKeys(); } catch (Throwable $e) { ErrorHandler::log('install', 'VAPID: ' . $e->getMessage()); }
        SystemController::buildIcons();

        json_out(['ok' => true, 'message' => 'Installed successfully.', 'redirect' => url($adminEmail !== '' ? '/login' : '/register')]);
    }
}
