-- =====================================================================
-- NovaShop seed data — import AFTER schema.sql
-- Creates: icon library, plugin/courier/tracking rows, sample catalog.
-- No admin account is seeded: create it securely at /admin/setup.
-- Sample products/categories can be deleted from the admin panel.
-- =====================================================================
SET NAMES utf8mb4;

INSERT IGNORE INTO `category_icons` (`icon_class`, `label`, `group_name`, `keywords`) VALUES
('fa-solid fa-shirt', 'Shirt', 'fashion', 'tshirt clothing'),
('fa-solid fa-person-dress', 'Dress', 'fashion', 'women ladies'),
('fa-solid fa-user-tie', 'Formal', 'fashion', 'suit men'),
('fa-solid fa-vest', 'Vest', 'fashion', 'clothing'),
('fa-solid fa-hat-cowboy', 'Hat', 'fashion', 'cap'),
('fa-solid fa-socks', 'Socks', 'fashion', 'clothing'),
('fa-solid fa-glasses', 'Glasses', 'fashion', 'eyewear'),
('fa-solid fa-ring', 'Ring', 'fashion', 'jewelry'),
('fa-solid fa-gem', 'Gem', 'fashion', 'jewelry diamond'),
('fa-solid fa-crown', 'Crown', 'fashion', 'premium'),
('fa-solid fa-bag-shopping', 'Bag', 'fashion', 'shopping'),
('fa-solid fa-briefcase', 'Briefcase', 'fashion', 'office bag'),
('fa-solid fa-shoe-prints', 'Shoes', 'fashion', 'footwear'),
('fa-solid fa-mitten', 'Mitten', 'fashion', 'winter'),
('fa-solid fa-scissors', 'Tailor', 'fashion', 'sewing'),
('fa-solid fa-person', 'Men', 'fashion', 'male'),
('fa-solid fa-person-half-dress', 'Unisex', 'fashion', 'women men'),
('fa-solid fa-child', 'Kids', 'fashion', 'children baby'),
('fa-solid fa-baby', 'Baby', 'fashion', 'infant'),
('fa-solid fa-baby-carriage', 'Baby Care', 'fashion', 'stroller'),
('fa-solid fa-mobile-screen', 'Mobile', 'electronics', 'phone smartphone'),
('fa-solid fa-laptop', 'Laptop', 'electronics', 'computer'),
('fa-solid fa-desktop', 'Desktop', 'electronics', 'computer monitor'),
('fa-solid fa-tablet-screen-button', 'Tablet', 'electronics', 'ipad'),
('fa-solid fa-headphones', 'Headphones', 'electronics', 'audio'),
('fa-solid fa-camera', 'Camera', 'electronics', 'photo'),
('fa-solid fa-tv', 'TV', 'electronics', 'television'),
('fa-solid fa-gamepad', 'Gaming', 'electronics', 'games console'),
('fa-solid fa-keyboard', 'Keyboard', 'electronics', 'computer accessories'),
('fa-solid fa-computer-mouse', 'Mouse', 'electronics', 'accessories'),
('fa-solid fa-plug', 'Accessories', 'electronics', 'charger cable'),
('fa-solid fa-battery-full', 'Battery', 'electronics', 'power bank'),
('fa-solid fa-microchip', 'Components', 'electronics', 'chip'),
('fa-solid fa-print', 'Printer', 'electronics', 'office'),
('fa-solid fa-satellite-dish', 'Network', 'electronics', 'wifi router'),
('fa-solid fa-clock', 'Watch', 'electronics', 'time'),
('fa-solid fa-lightbulb', 'Lighting', 'electronics', 'bulb lamp'),
('fa-solid fa-fan', 'Fan', 'electronics', 'cooling'),
('fa-solid fa-blender', 'Kitchen Appliance', 'electronics', 'blender'),
('fa-solid fa-camera-retro', 'Vintage Camera', 'electronics', 'photo'),
('fa-solid fa-house', 'Home', 'home', 'house'),
('fa-solid fa-couch', 'Furniture', 'home', 'sofa'),
('fa-solid fa-bed', 'Bedding', 'home', 'bed'),
('fa-solid fa-chair', 'Chair', 'home', 'furniture'),
('fa-solid fa-kitchen-set', 'Kitchen', 'home', 'cookware'),
('fa-solid fa-utensils', 'Dining', 'home', 'utensils'),
('fa-solid fa-mug-hot', 'Mug', 'home', 'tea coffee'),
('fa-solid fa-bath', 'Bath', 'home', 'bathroom'),
('fa-solid fa-broom', 'Cleaning', 'home', 'household'),
('fa-solid fa-seedling', 'Garden', 'home', 'plants'),
('fa-solid fa-hammer', 'Tools', 'home', 'hardware'),
('fa-solid fa-screwdriver-wrench', 'Repair', 'home', 'tools'),
('fa-solid fa-paint-roller', 'Decor', 'home', 'paint'),
('fa-solid fa-rug', 'Rug', 'home', 'carpet'),
('fa-solid fa-sink', 'Sink', 'home', 'kitchen'),
('fa-solid fa-spa', 'Beauty', 'beauty', 'spa'),
('fa-solid fa-pump-soap', 'Skin Care', 'beauty', 'soap'),
('fa-solid fa-spray-can-sparkles', 'Perfume', 'beauty', 'fragrance'),
('fa-solid fa-heart-pulse', 'Health', 'beauty', 'medical'),
('fa-solid fa-pills', 'Medicine', 'beauty', 'pharmacy'),
('fa-solid fa-hand-sparkles', 'Hand Care', 'beauty', 'hygiene'),
('fa-solid fa-wand-magic-sparkles', 'Cosmetics', 'beauty', 'makeup'),
('fa-solid fa-leaf', 'Organic', 'beauty', 'natural herbal'),
('fa-solid fa-dumbbell', 'Fitness', 'beauty', 'gym sports'),
('fa-solid fa-person-running', 'Sports', 'beauty', 'running'),
('fa-solid fa-apple-whole', 'Fruits', 'food', 'food'),
('fa-solid fa-carrot', 'Vegetables', 'food', 'food'),
('fa-solid fa-fish', 'Fish', 'food', 'seafood'),
('fa-solid fa-drumstick-bite', 'Meat', 'food', 'chicken'),
('fa-solid fa-bread-slice', 'Bakery', 'food', 'bread'),
('fa-solid fa-cheese', 'Dairy', 'food', 'cheese'),
('fa-solid fa-egg', 'Egg', 'food', 'food'),
('fa-solid fa-cookie', 'Snacks', 'food', 'cookie'),
('fa-solid fa-ice-cream', 'Dessert', 'food', 'sweets'),
('fa-solid fa-mug-saucer', 'Beverage', 'food', 'tea'),
('fa-solid fa-bottle-water', 'Water', 'food', 'drinks'),
('fa-solid fa-jar', 'Grocery', 'food', 'jar honey'),
('fa-solid fa-wheat-awn', 'Rice & Grain', 'food', 'rice'),
('fa-solid fa-pepper-hot', 'Spices', 'food', 'masala'),
('fa-solid fa-candy-cane', 'Candy', 'food', 'sweets'),
('fa-solid fa-book', 'Books', 'other', 'reading'),
('fa-solid fa-pen', 'Stationery', 'other', 'pen'),
('fa-solid fa-graduation-cap', 'Education', 'other', 'school'),
('fa-solid fa-gift', 'Gifts', 'other', 'present'),
('fa-solid fa-car', 'Automobile', 'other', 'car'),
('fa-solid fa-motorcycle', 'Bike', 'other', 'motorcycle'),
('fa-solid fa-bicycle', 'Bicycle', 'other', 'cycle'),
('fa-solid fa-paw', 'Pet', 'other', 'animals'),
('fa-solid fa-futbol', 'Football', 'other', 'sports'),
('fa-solid fa-guitar', 'Music', 'other', 'instrument'),
('fa-solid fa-palette', 'Art', 'other', 'craft'),
('fa-solid fa-puzzle-piece', 'Toys', 'other', 'kids games'),
('fa-solid fa-mosque', 'Islamic', 'other', 'religious'),
('fa-solid fa-star', 'Featured', 'other', 'special'),
('fa-solid fa-bolt', 'Flash', 'other', 'sale'),
('fa-solid fa-fire', 'Trending', 'other', 'hot'),
('fa-solid fa-tag', 'Tag', 'other', 'offer'),
('fa-solid fa-tags', 'Offers', 'other', 'deals'),
('fa-solid fa-percent', 'Discount', 'other', 'sale'),
('fa-solid fa-box', 'Box', 'other', 'package'),
('fa-solid fa-boxes-stacked', 'Combo', 'other', 'bundle'),
('fa-solid fa-layer-group', 'Collection', 'other', 'combo'),
('fa-solid fa-truck', 'Delivery', 'other', 'shipping'),
('fa-solid fa-umbrella', 'Umbrella', 'other', 'rain'),
('fa-solid fa-suitcase-rolling', 'Travel', 'other', 'luggage');

INSERT IGNORE INTO `tracking_settings` (`provider`, `event_name`, `browser_enabled`, `server_enabled`) VALUES
('meta', 'PageView', 1, 0),
('meta', 'ViewContent', 1, 1),
('meta', 'AddToCart', 1, 1),
('meta', 'InitiateCheckout', 1, 1),
('meta', 'Purchase', 1, 1),
('google', 'page_view', 1, 0),
('google', 'view_item', 1, 0),
('google', 'add_to_cart', 1, 0),
('google', 'begin_checkout', 1, 0),
('google', 'purchase', 1, 0);

INSERT IGNORE INTO `plugins` (`slug`, `name`, `category`, `is_enabled`) VALUES
('meta_pixel', 'Meta Pixel', 'tracking', 0),
('meta_capi', 'Meta Conversions API', 'tracking', 0),
('google_tag', 'Google Tag Manager', 'tracking', 0),
('google_ads', 'Google Ads Conversion', 'tracking', 0),
('fraud_check', 'Fraud Check', 'security', 1),
('whatsapp', 'WhatsApp', 'support', 1);

INSERT IGNORE INTO `couriers` (`slug`, `name`, `is_enabled`, `is_default`) VALUES
('bdcourier', 'BD Courier', 0, 0),
('steadfast', 'Steadfast', 0, 1),
('pathao', 'Pathao', 0, 0),
('redx', 'RedX', 0, 0);

-- Sample catalog -------------------------------------------------------
INSERT IGNORE INTO `categories` (`id`, `parent_id`, `name`, `slug`, `description`, `icon_type`, `icon`, `status`, `sort_order`) VALUES
(1, NULL, 'পুরুষদের ফ্যাশন', 'mens-fashion', 'শার্ট, পাঞ্জাবি, টি-শার্ট ও আরও অনেক কিছু।', 'fa', 'fa-solid fa-shirt', 'active', 1),
(2, NULL, 'মেয়েদের ফ্যাশন', 'womens-fashion', 'থ্রি-পিস, শাড়ি, কুর্তি ও এক্সেসরিজ।', 'fa', 'fa-solid fa-person-dress', 'active', 2),
(3, NULL, 'ইলেকট্রনিক্স', 'electronics', 'গ্যাজেট ও এক্সেসরিজ।', 'fa', 'fa-solid fa-headphones', 'active', 3),
(4, NULL, 'ঘর ও রান্নাঘর', 'home-kitchen', 'প্রয়োজনীয় গৃহস্থালি পণ্য।', 'fa', 'fa-solid fa-kitchen-set', 'active', 4),
(5, NULL, 'বিউটি ও কেয়ার', 'beauty-care', 'স্কিন কেয়ার ও পার্সোনাল কেয়ার।', 'fa', 'fa-solid fa-spa', 'active', 5),
(6, NULL, 'অর্গানিক ফুড', 'organic-food', 'খাঁটি ও প্রাকৃতিক খাদ্যপণ্য।', 'fa', 'fa-solid fa-leaf', 'active', 6),
(7, 1, 'পাঞ্জাবি', 'panjabi', 'উৎসবের পাঞ্জাবি কালেকশন।', 'fa', 'fa-solid fa-user-tie', 'active', 1),
(8, 3, 'স্মার্ট ওয়াচ', 'smart-watch', 'স্মার্ট ওয়াচ ও ফিটনেস ব্যান্ড।', 'fa', 'fa-solid fa-clock', 'active', 2);

INSERT IGNORE INTO `products` (`id`, `category_id`, `subcategory_id`, `name`, `slug`, `sku`, `short_description`, `description`, `specifications`, `features`, `tags`, `price`, `old_price`, `stock`, `sizes`, `colors`, `is_free_delivery`, `is_featured`, `is_flash_sale`, `is_combo`, `sort_order`, `sold_count`) VALUES
(1, 1, NULL, 'প্রিমিয়াম কটন পোলো শার্ট', 'premium-cotton-polo-shirt', 'NS-POLO-01', '১০০% কটন, আরামদায়ক ও টেকসই পোলো শার্ট।', '<h3>কেন কিনবেন?</h3><p>নরম ও আরামদায়ক <strong>১০০% কটন</strong> কাপড়। প্রতিদিনের ব্যবহারের জন্য উপযুক্ত।</p><ul><li>রং উঠবে না</li><li>মেশিন ওয়াশেবল</li></ul>', '[{"label":"কাপড়","value":"১০০% কটন"},{"label":"ফিট","value":"রেগুলার"}]', '["আরামদায়ক কাপড়","দীর্ঘস্থায়ী রং","সব ঋতুর জন্য"]', 'polo,shirt,cotton', 850.00, 1200.00, 60, '["M","L","XL","XXL"]', '[{"name":"নেভি","hex":"#1e3a8a"},{"name":"সাদা","hex":"#f8fafc"}]', 0, 1, 1, 0, 1, 42),
(2, 1, 7, 'এমব্রয়ডারি কাজ করা ঈদ পাঞ্জাবি', 'embroidery-eid-panjabi', 'NS-PNJ-02', 'সূক্ষ্ম এমব্রয়ডারি কাজ করা প্রিমিয়াম পাঞ্জাবি।', '<p>উৎসবের জন্য বিশেষভাবে তৈরি <strong>প্রিমিয়াম পাঞ্জাবি</strong>।</p>', '[{"label":"কাপড়","value":"সুতি মিক্স"}]', '["হাতের কাজ","প্রিমিয়াম ফিনিশিং"]', 'panjabi,eid', 1850.00, 2500.00, 25, '["38","40","42","44"]', '[]', 1, 1, 0, 0, 2, 18),
(3, 2, NULL, 'জর্জেট থ্রি-পিস', 'georgette-three-piece', 'NS-3P-03', 'আনস্টিচড জর্জেট থ্রি-পিস, সুন্দর প্রিন্ট।', '<p>উন্নত মানের জর্জেট কাপড়ে তৈরি থ্রি-পিস।</p>', '[]', '["আনস্টিচড","ডিজিটাল প্রিন্ট"]', 'three piece,dress', 1450.00, 1900.00, 30, '[]', '[]', 0, 1, 1, 0, 3, 27),
(4, 3, 8, 'স্মার্ট ওয়াচ প্রো (ব্লুটুথ কলিং)', 'smart-watch-pro-bluetooth-calling', 'NS-SW-04', 'ব্লুটুথ কলিং, হার্ট রেট ও স্লিপ মনিটর।', '<p>১.৮৫ ইঞ্চি ডিসপ্লে, ৭ দিন পর্যন্ত ব্যাটারি ব্যাকআপ।</p>', '[{"label":"ডিসপ্লে","value":"1.85 ইঞ্চি IPS"},{"label":"ব্যাটারি","value":"৭ দিন"},{"label":"ওয়াটারপ্রুফ","value":"IP67"}]', '["ব্লুটুথ কলিং","১০০+ ওয়াচ ফেস","হার্ট রেট মনিটর"]', 'watch,smart watch', 2490.00, 3500.00, 8, '[]', '[{"name":"কালো","hex":"#111827"},{"name":"সিলভার","hex":"#cbd5e1"}]', 1, 1, 1, 0, 4, 64),
(5, 3, NULL, 'ওয়্যারলেস ইয়ারবাডস TWS', 'wireless-earbuds-tws', 'NS-EB-05', 'নয়েজ রিডাকশন সহ ট্রু ওয়্যারলেস ইয়ারবাডস।', '<p>পরিষ্কার সাউন্ড ও শক্তিশালী বেস।</p>', '[{"label":"ব্লুটুথ","value":"5.3"},{"label":"ব্যাটারি","value":"২৪ ঘণ্টা (কেস সহ)"}]', '["টাচ কন্ট্রোল","লো ল্যাটেন্সি"]', 'earbuds,tws,headphone', 1290.00, 1800.00, 45, '[]', '[]', 0, 0, 1, 0, 5, 51),
(6, 4, NULL, 'নন-স্টিক কুকওয়্যার সেট (৫ পিস)', 'non-stick-cookware-set-5-pcs', 'NS-CK-06', '৫ পিসের নন-স্টিক কুকওয়্যার সেট।', '<p>স্বাস্থ্যকর রান্নার জন্য নন-স্টিক কোটিং।</p>', '[]', '["৫ পিস","গ্যাস ও ইন্ডাকশন উপযোগী"]', 'cookware,kitchen', 3200.00, 4200.00, 12, '[]', '[]', 1, 0, 0, 1, 6, 9),
(7, 5, NULL, 'ভিটামিন সি ফেস সিরাম + ময়েশ্চারাইজার কম্বো', 'vitamin-c-serum-moisturizer-combo', 'NS-BC-07', 'উজ্জ্বল ত্বকের জন্য কম্বো প্যাক।', '<p>ভিটামিন সি সিরাম ও ময়েশ্চারাইজারের কার্যকর কম্বো।</p>', '[]', '["সব ধরনের ত্বকে উপযোগী"]', 'serum,skin care,combo', 990.00, 1400.00, 40, '[]', '[]', 0, 1, 0, 1, 7, 33),
(8, 6, NULL, 'খাঁটি সুন্দরবনের মধু (১ কেজি)', 'pure-sundarban-honey-1kg', 'NS-HN-08', '১০০% খাঁটি প্রাকৃতিক মধু।', '<p>সুন্দরবন থেকে সংগৃহীত খাঁটি মধু।</p>', '[{"label":"ওজন","value":"১ কেজি"}]', '["কোনো ভেজাল নেই","ল্যাব টেস্টেড"]', 'honey,organic', 1100.00, NULL, 100, '[]', '[]', 1, 0, 0, 0, 8, 75),
(9, 6, NULL, 'অর্গানিক খেজুর ও বাদাম কম্বো প্যাক', 'organic-dates-nuts-combo', 'NS-DT-09', 'খেজুর, কাজুবাদাম ও কাঠবাদামের স্বাস্থ্যকর কম্বো।', '<p>পরিবারের জন্য পুষ্টিকর কম্বো প্যাক।</p>', '[]', '["প্রিমিয়াম কোয়ালিটি"]', 'dates,nuts,combo', 1650.00, 2100.00, 20, '[]', '[]', 0, 0, 0, 1, 9, 14),
(10, 2, NULL, 'হ্যান্ডপেইন্টেড সুতি শাড়ি', 'handpainted-cotton-saree', 'NS-SR-10', 'আরামদায়ক হ্যান্ডপেইন্টেড সুতি শাড়ি।', '<p>নিখুঁত হাতের কাজে তৈরি শাড়ি।</p>', '[]', '["হাতে আঁকা ডিজাইন"]', 'saree', 2200.00, 2800.00, 0, '[]', '[]', 0, 0, 0, 0, 10, 6);

INSERT IGNORE INTO `product_variants` (`product_id`, `size`, `color`, `stock`) VALUES
(1, 'M', 'নেভি', 8), (1, 'L', 'নেভি', 8), (1, 'XL', 'নেভি', 7), (1, 'XXL', 'নেভি', 7),
(1, 'M', 'সাদা', 8), (1, 'L', 'সাদা', 8), (1, 'XL', 'সাদা', 7), (1, 'XXL', 'সাদা', 7),
(2, '38', '', 6), (2, '40', '', 7), (2, '42', '', 7), (2, '44', '', 5),
(4, '', 'কালো', 5), (4, '', 'সিলভার', 3);

INSERT IGNORE INTO `coupons` (`code`, `description`, `type`, `value`, `min_order`, `max_discount`, `is_active`, `show_on_home`) VALUES
('WELCOME10', 'প্রথম অর্ডারে ১০% ছাড় (সর্বোচ্চ ২০০ টাকা)', 'percent', 10, 500, 200, 1, 1);
