<?php
/**
 * One-time web installer (/install). Runs only while config/config.local.php
 * does not exist. Checks requirements, imports database/database.sql,
 * creates the first super-admin and writes config.local.php.
 */
declare(strict_types=1);

function install_split_sql(string $sql): array
{
    $out = [];
    $buf = '';
    $len = strlen($sql);
    $quote = null;
    for ($i = 0; $i < $len; $i++) {
        $c = $sql[$i];
        if ($quote === null) {
            if ($c === '-' && ($sql[$i + 1] ?? '') === '-') {
                $nl = strpos($sql, "\n", $i);
                $i = $nl === false ? $len : $nl;
                continue;
            }
            if ($c === "'" || $c === '"' || $c === '`') {
                $quote = $c;
            } elseif ($c === ';') {
                if (trim($buf) !== '') {
                    $out[] = trim($buf);
                }
                $buf = '';
                continue;
            }
        } elseif ($c === '\\') {
            $buf .= $c . ($sql[$i + 1] ?? '');
            $i++;
            continue;
        } elseif ($c === $quote) {
            if (($sql[$i + 1] ?? '') === $quote) {
                $buf .= $c . $c;
                $i++;
                continue;
            }
            $quote = null;
        }
        $buf .= $c;
    }
    if (trim($buf) !== '') {
        $out[] = trim($buf);
    }
    return $out;
}

$checks = [
    'PHP 8.0 বা নতুন' => version_compare(PHP_VERSION, '8.0.0', '>='),
    'PDO MySQL' => extension_loaded('pdo_mysql'),
    'OpenSSL' => extension_loaded('openssl'),
    'Sodium' => extension_loaded('sodium'),
    'cURL' => extension_loaded('curl'),
    'mbstring' => extension_loaded('mbstring'),
    'GD (ইমেজ)' => extension_loaded('gd'),
    'fileinfo' => extension_loaded('fileinfo'),
    'config/ লেখার অনুমতি' => is_writable(ROOT . '/config'),
    'storage/ লেখার অনুমতি' => is_writable(ROOT . '/storage') && is_writable(ROOT . '/storage/cache') && is_writable(ROOT . '/storage/logs'),
    'uploads/ লেখার অনুমতি' => is_writable(ROOT . '/uploads'),
];
$allOk = !in_array(false, $checks, true);
$error = '';
$done = false;

if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST') {
    if (!hash_equals(csrf_token(), (string) ($_POST['_csrf'] ?? ''))) {
        $error = 'সেশনের মেয়াদ শেষ। পেজ রিফ্রেশ করে আবার চেষ্টা করুন।';
    } elseif (!$allOk) {
        $error = 'সার্ভারের প্রয়োজনীয়তা পূরণ হয়নি।';
    } else {
        $db = [
            'host' => trim((string) ($_POST['db_host'] ?? 'localhost')),
            'port' => (int) ($_POST['db_port'] ?? 3306) ?: 3306,
            'name' => trim((string) ($_POST['db_name'] ?? '')),
            'user' => trim((string) ($_POST['db_user'] ?? '')),
            'pass' => (string) ($_POST['db_pass'] ?? ''),
            'charset' => 'utf8mb4',
        ];
        $adminName = trim((string) ($_POST['admin_name'] ?? ''));
        $adminEmail = strtolower(trim((string) ($_POST['admin_email'] ?? '')));
        $adminPass = (string) ($_POST['admin_pass'] ?? '');
        if ($db['name'] === '' || $db['user'] === '') {
            $error = 'ডাটাবেসের নাম ও ইউজার দিন।';
        } elseif ($adminName === '' || !filter_var($adminEmail, FILTER_VALIDATE_EMAIL) || strlen($adminPass) < 10) {
            $error = 'অ্যাডমিনের নাম, সঠিক ইমেইল এবং কমপক্ষে ১০ অক্ষরের পাসওয়ার্ড দিন।';
        } else {
            try {
                $pdo = new PDO(sprintf('mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4', $db['host'], $db['port'], $db['name']), $db['user'], $db['pass'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
                $pdo->exec('SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci');
                $pdo->exec("ALTER DATABASE `" . str_replace('`', '', $db['name']) . "` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
                foreach (install_split_sql((string) file_get_contents(ROOT . '/database/database.sql')) as $stmt) {
                    $pdo->exec($stmt);
                }
                $appKey = base64_encode(random_bytes(32));
                $GLOBALS['CONFIG']['db'] = $db;
                $GLOBALS['CONFIG']['app_key'] = $appKey;
                $GLOBALS['CONFIG']['installed'] = true;
                if (!$pdo->query('SELECT COUNT(*) FROM admin_users')->fetchColumn()) {
                    $st = $pdo->prepare("INSERT INTO admin_users (name, email, password_hash, role) VALUES (?, ?, ?, 'super')");
                    $st->execute([$adminName, $adminEmail, password_hash($adminPass, PASSWORD_DEFAULT)]);
                }
                if (WebPush::publicKey() === '') {
                    WebPush::generateKeys();
                }
                Settings::set('contact_email', $adminEmail);
                Settings::set('push_subject', 'mailto:' . $adminEmail);
                $config = "<?php\n// Generated by the installer on " . date('Y-m-d H:i') . ". Keep this file private.\nreturn " . var_export([
                    'installed' => true,
                    'env' => 'production',
                    'db' => $db,
                    'app_key' => $appKey,
                    'base_url' => rtrim(trim((string) ($_POST['base_url'] ?? '')), '/'),
                    'force_https' => !empty($_POST['force_https']),
                ], true) . ";\n";
                if (file_put_contents(ROOT . '/config/config.local.php', $config, LOCK_EX) === false) {
                    throw new RuntimeException('config.local.php লেখা যায়নি');
                }
                @chmod(ROOT . '/config/config.local.php', 0640);
                $done = true;
            } catch (Throwable $e) {
                Logger::error($e);
                $error = 'ইনস্টল সম্পন্ন হয়নি: ' . ($e instanceof PDOException ? 'ডাটাবেস সংযোগ/ইমপোর্ট ব্যর্থ — তথ্য যাচাই করুন।' : $e->getMessage());
            }
        }
    }
}
$v = static fn (string $k, string $d = '') => e($_POST[$k] ?? $d);
header('Content-Type: text/html; charset=utf-8');
?><!doctype html>
<html lang="bn"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex">
<title>Probaho — ইনস্টলার</title>
<link rel="stylesheet" href="<?= e(asset('css/app.css')) ?>">
</head><body>
<div class="auth-wrap" style="min-height:100vh"><div class="auth-card" style="max-width:560px">
<div class="card">
  <div class="auth-head"><img src="<?= e(url('assets/images/logo.svg')) ?>" class="brand-logo" alt="" width="52" height="52"><h1>Probaho ইনস্টলার</h1><p>কয়েকটি তথ্য দিয়ে আপনার পেমেন্ট প্ল্যাটফর্ম চালু করুন</p></div>
  <?php if ($done): ?>
    <div class="alert alert-ok"><div><b>ইনস্টল সম্পন্ন হয়েছে ✓</b><br>নিরাপত্তার জন্য প্রয়োজনে <code>includes/installer.php</code> মুছে ফেলতে পারেন। এখন অ্যাডমিন প্যানেলে লগইন করে SMTP, Binance Pay, Google লগইন ও সাপোর্ট সেটিংস কনফিগার করুন।</div></div>
    <div class="row" style="margin-top:16px"><a class="btn btn-ghost grow" href="<?= e(url('/')) ?>">ওয়েবসাইট</a><a class="btn btn-primary grow" href="<?= e(url('/v2admin/login')) ?>">অ্যাডমিন প্যানেল</a></div>
  <?php else: ?>
    <div class="list" style="margin-bottom:16px">
      <?php foreach ($checks as $label => $pass): ?>
        <div class="list-item"><span class="li-main"><?= e($label) ?></span><?= $pass ? '<span class="badge badge-ok">ঠিক আছে</span>' : '<span class="badge badge-err">প্রয়োজন</span>' ?></div>
      <?php endforeach; ?>
    </div>
    <?php if ($error): ?><div class="form-error"><?= e($error) ?></div><?php endif; ?>
    <form method="post" autocomplete="off">
      <input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>">
      <h3 style="font-size:16px">ডাটাবেস (MySQL / MariaDB)</h3>
      <div class="row"><div class="field grow"><label>হোস্ট</label><input class="input" name="db_host" value="<?= $v('db_host', 'localhost') ?>" required></div><div class="field" style="width:110px"><label>পোর্ট</label><input class="input" name="db_port" value="<?= $v('db_port', '3306') ?>"></div></div>
      <div class="field"><label>ডাটাবেসের নাম</label><input class="input" name="db_name" value="<?= $v('db_name') ?>" required></div>
      <div class="row"><div class="field grow"><label>ইউজার</label><input class="input" name="db_user" value="<?= $v('db_user') ?>" required></div><div class="field grow"><label>পাসওয়ার্ড</label><input class="input" type="password" name="db_pass"></div></div>
      <h3 style="font-size:16px;margin-top:8px">সাইট</h3>
      <div class="field"><label>সাইটের URL (ঐচ্ছিক)</label><input class="input" name="base_url" value="<?= $v('base_url', origin()) ?>" placeholder="https://pay.example.com"><div class="hint">Passkey ও Push-এর জন্য HTTPS প্রয়োজন।</div></div>
      <label class="check" style="margin-bottom:14px"><input type="checkbox" name="force_https" value="1" <?= is_https() ? 'checked' : '' ?>> সবসময় HTTPS ব্যবহার করুন</label>
      <h3 style="font-size:16px">প্রথম অ্যাডমিন (Super Admin)</h3>
      <div class="field"><label>নাম</label><input class="input" name="admin_name" value="<?= $v('admin_name') ?>" required></div>
      <div class="field"><label>ইমেইল</label><input class="input" type="email" name="admin_email" value="<?= $v('admin_email') ?>" required></div>
      <div class="field"><label>পাসওয়ার্ড (কমপক্ষে ১০ অক্ষর)</label><input class="input" type="password" name="admin_pass" minlength="10" required></div>
      <button class="btn btn-primary btn-block btn-lg" <?= $allOk ? '' : 'disabled' ?>>ইনস্টল করুন</button>
    </form>
  <?php endif; ?>
</div></div></div>
</body></html>
