import { createBrowserRouter, type RouteObject } from 'react-router';
import { RouteError } from './store/pages/ErrorPages';

/** Every page is code-split; the admin bundle never loads for shoppers. */
const lazy = (loader: () => Promise<{ default: React.ComponentType }>): RouteObject['lazy'] => async () => ({ Component: (await loader()).default });

export const router = createBrowserRouter([
  { path: '/install', lazy: lazy(() => import('./install/Installer')) },
  { path: '/admin/login', lazy: lazy(() => import('./admin/Login')) },
  {
    path: '/admin',
    lazy: lazy(() => import('./admin/AdminLayout')),
    errorElement: <RouteError />,
    children: [
      { index: true, lazy: lazy(() => import('./admin/pages/Dashboard')) },
      { path: 'orders', lazy: lazy(() => import('./admin/pages/Orders')) },
      { path: 'orders/:id', lazy: lazy(() => import('./admin/pages/OrderDetail')) },
      { path: 'orders/:id/print', lazy: lazy(() => import('./admin/pages/OrderPrint')) },
      { path: 'products', lazy: lazy(() => import('./admin/pages/Products')) },
      { path: 'products/new', lazy: lazy(() => import('./admin/pages/ProductEdit')) },
      { path: 'products/:id', lazy: lazy(() => import('./admin/pages/ProductEdit')) },
      { path: 'categories', lazy: lazy(() => import('./admin/pages/Categories')) },
      { path: 'brands', lazy: lazy(() => import('./admin/pages/Brands')) },
      { path: 'reviews', lazy: lazy(() => import('./admin/pages/Reviews')) },
      { path: 'banners', lazy: lazy(() => import('./admin/pages/Banners')) },
      { path: 'coupons', lazy: lazy(() => import('./admin/pages/Coupons')) },
      { path: 'flash-sales', lazy: lazy(() => import('./admin/pages/FlashSales')) },
      { path: 'combos', lazy: lazy(() => import('./admin/pages/Combos')) },
      { path: 'home-sections', lazy: lazy(() => import('./admin/pages/HomeSections')) },
      { path: 'delivery', lazy: lazy(() => import('./admin/pages/Delivery')) },
      { path: 'customers', lazy: lazy(() => import('./admin/pages/Customers')) },
      { path: 'customers/:id', lazy: lazy(() => import('./admin/pages/CustomerDetail')) },
      { path: 'couriers', lazy: lazy(() => import('./admin/pages/Couriers')) },
      { path: 'fraud', lazy: lazy(() => import('./admin/pages/Fraud')) },
      { path: 'analytics', lazy: lazy(() => import('./admin/pages/Analytics')) },
      { path: 'pages', lazy: lazy(() => import('./admin/pages/Pages')) },
      { path: 'settings', lazy: lazy(() => import('./admin/pages/Settings')) },
      { path: 'security', lazy: lazy(() => import('./admin/pages/Security')) },
      { path: 'admins', lazy: lazy(() => import('./admin/pages/Admins')) },
      { path: 'audit', lazy: lazy(() => import('./admin/pages/Audit')) },
      { path: 'trash', lazy: lazy(() => import('./admin/pages/Trash')) },
      { path: 'notifications', lazy: lazy(() => import('./admin/pages/Notifications')) },
      { path: 'system/backups', lazy: lazy(() => import('./admin/pages/Backups')) },
      { path: 'system/updates', lazy: lazy(() => import('./admin/pages/Updates')) },
      { path: 'system/health', lazy: lazy(() => import('./admin/pages/Health')) },
      { path: 'more', lazy: lazy(() => import('./admin/pages/More')) },
      { path: '*', lazy: lazy(() => import('./admin/pages/AdminNotFound')) },
    ],
  },
  {
    path: '/',
    lazy: lazy(() => import('./store/StoreLayout')),
    errorElement: <RouteError />,
    children: [
      { index: true, lazy: lazy(() => import('./store/pages/Home')) },
      { path: 'categories', lazy: lazy(() => import('./store/pages/Categories')) },
      { path: 'category/:slug', lazy: lazy(() => import('./store/pages/Listing')) },
      { path: 'search', lazy: lazy(() => import('./store/pages/Listing')) },
      { path: 'products', lazy: lazy(() => import('./store/pages/Listing')) },
      { path: 'flash-sale', lazy: lazy(() => import('./store/pages/Listing')) },
      { path: 'product/:slug', lazy: lazy(() => import('./store/pages/Product')) },
      { path: 'combos', lazy: lazy(() => import('./store/pages/Combos')) },
      { path: 'combo/:slug', lazy: lazy(() => import('./store/pages/Combo')) },
      { path: 'cart', lazy: lazy(() => import('./store/pages/Cart')) },
      { path: 'checkout', lazy: lazy(() => import('./store/pages/Checkout')) },
      { path: 'order/:orderNo', lazy: lazy(() => import('./store/pages/OrderSuccess')) },
      { path: 'track', lazy: lazy(() => import('./store/pages/Track')) },
      { path: 'wishlist', lazy: lazy(() => import('./store/pages/Wishlist')) },
      { path: 'contact', lazy: lazy(() => import('./store/pages/Contact')) },
      { path: 'page/:slug', lazy: lazy(() => import('./store/pages/Page')) },
      { path: 'offline', lazy: lazy(() => import('./store/pages/Offline')) },
      { path: '*', lazy: lazy(() => import('./store/pages/NotFound')) },
    ],
  },
]);
