<?php
final class Env
{
    private static array $vars = [];

    public static function load(string $file): void
    {
        if (!is_file($file)) {
            return;
        }
        foreach (file($file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
            $line = trim($line);
            if ($line === '' || $line[0] === '#' || !str_contains($line, '=')) {
                continue;
            }
            [$k, $v] = explode('=', $line, 2);
            $v = trim($v);
            if (strlen($v) >= 2 && ($v[0] === '"' || $v[0] === "'") && $v[-1] === $v[0]) {
                $v = stripcslashes(substr($v, 1, -1));
            }
            self::$vars[trim($k)] = $v;
        }
    }

    public static function get(string $key, ?string $default = null): ?string
    {
        return self::$vars[$key] ?? $default;
    }

    public static function write(string $file, array $values): bool
    {
        $out = "# Generated by installer on " . date('Y-m-d H:i:s') . "\n";
        foreach ($values as $k => $v) {
            $v = (string) $v;
            $out .= $k . '="' . addcslashes($v, "\"\\\n\r\$") . "\"\n";
        }
        $ok = file_put_contents($file, $out, LOCK_EX) !== false;
        if ($ok) {
            @chmod($file, 0600);
        }
        return $ok;
    }
}
