'use strict';
/**
 * 10-step installation wizard backend. Only reachable while install/installed.lock
 * does not exist. The first browser to open /install receives an installer key
 * cookie; all installer API calls must present it (plus INSTALL_TOKEN when set).
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const paths = require('../config/paths');
const config = require('../config/env');
const db = require('../config/database');
const settings = require('../models/settings');
const User = require('../models/user');
const fileStorage = require('../services/fileStorage');
const { migrate } = require('../utils/migrate');
const { seed } = require('../utils/seed');
const { encrypt, safeEqual } = require('../utils/crypto');
const v = require('../utils/validate');
const { E } = require('../utils/errors');

const state = { key: null, startedAt: 0, done: {} };
const COOKIE = 'aura_install';

function readCookie(req, name) {
  const raw = req.get('cookie') || '';
  for (const part of raw.split(';')) {
    const [k, ...rest] = part.trim().split('=');
    if (k === name) return decodeURIComponent(rest.join('='));
  }
  return null;
}

// APP_INSTALLED=true lets hosts that wipe the filesystem on redeploy (e.g. Hostinger) stay installed.
function isInstalled() { return fs.existsSync(paths.INSTALL_LOCK) || config.bool(process.env.APP_INSTALLED); }

/** GET /install — issue the installer key to the first visitor. */
function page(req, res) {
  if (isInstalled()) return res.redirect('/login');
  if (config.installToken && !safeEqual(req.query.token || '', config.installToken) && !safeEqual(readCookie(req, COOKIE) || '', state.key || '')) {
    return res.status(403).type('text').send('Installer locked: open /install?token=<INSTALL_TOKEN>');
  }
  const current = readCookie(req, COOKIE);
  const expired = state.key && Date.now() - state.startedAt > 2 * 3600_000;
  if (!state.key || expired) {
    state.key = crypto.randomBytes(24).toString('hex');
    state.startedAt = Date.now();
    state.done = {};
  } else if (!safeEqual(current || '', state.key)) {
    return res.status(423).type('text').send('Another browser is currently running the installer. Finish it there, or restart the server to reset.');
  }
  res.cookie(COOKIE, state.key, { httpOnly: true, sameSite: 'strict', path: '/install', maxAge: 2 * 3600_000 });
  res.sendFile(path.join(paths.INSTALL_DIR, 'index.html'));
}

function guard(req, res, next) {
  if (isInstalled()) return next(E.forbidden('Application is already installed'));
  if (!state.key || !safeEqual(readCookie(req, COOKIE) || '', state.key)) return next(E.forbidden('Installer session expired — reload /install'));
  if (req.method !== 'GET' && req.get('x-installer') !== '1') return next(E.forbidden('Bad installer request'));
  next();
}

function envLine(k, val) {
  const s = String(val ?? '');
  if (/^[\w@%+=:,./-]*$/.test(s)) return `${k}=${s}`;
  if (!s.includes("'") && !/[\r\n]/.test(s)) return `${k}='${s}'`;
  throw E.badRequest(`${k} contains unsupported characters (quotes/newlines)`);
}

function writeEnv(values) {
  const dotenv = require('dotenv');
  const existing = fs.existsSync(paths.ENV_FILE) ? dotenv.parse(fs.readFileSync(paths.ENV_FILE)) : {};
  const merged = { ...existing, ...values };
  const order = ['NODE_ENV', 'PORT', 'APP_URL', 'DB_HOST', 'DB_PORT', 'DB_NAME', 'DB_USER', 'DB_PASSWORD', 'SESSION_SECRET', 'ENCRYPTION_KEY'];
  const keys = [...order.filter((k) => k in merged), ...Object.keys(merged).filter((k) => !order.includes(k))];
  const body = `# Generated by the Premium Aura installer on ${new Date().toISOString()}\n${keys.map((k) => envLine(k, merged[k])).join('\n')}\n`;
  fs.writeFileSync(paths.ENV_FILE, body, { mode: 0o600 });
  config.reload();
}

exports.page = page;
exports.guard = guard;
exports.isInstalled = isInstalled;

exports.requirements = async (req, res) => {
  const writable = (p) => { try { fs.mkdirSync(p, { recursive: true }); fs.accessSync(p, fs.constants.W_OK); return true; } catch { return false; } };
  const major = Number(process.versions.node.split('.')[0]);
  const checks = [
    { name: 'Node.js ≥ 18.17', ok: major >= 18, value: process.versions.node },
    { name: 'Project root writable (.env)', ok: writable(paths.ROOT), value: paths.ROOT },
    { name: 'uploads/ writable', ok: writable(paths.UPLOADS_DIR) },
    { name: 'logs/ writable', ok: writable(paths.LOGS_DIR) },
    { name: 'install/ writable (lock file)', ok: writable(paths.INSTALL_DIR) },
    { name: 'Native fetch available', ok: typeof fetch === 'function' },
    { name: 'Image compression (sharp)', ok: fileStorage.hasSharp(), optional: true, value: fileStorage.hasSharp() ? 'available' : 'optional — images stored as-is' },
  ];
  state.done.requirements = checks.every((c) => c.ok || c.optional);
  res.json({ ok: true, passed: state.done.requirements, checks });
};

exports.database = async (req, res) => {
  const b = req.body;
  const dbc = {
    host: v.str(b.host || '127.0.0.1', { name: 'Host', required: true, max: 190, pattern: /^[\w.-]+$/ }),
    port: v.int(b.port, { name: 'Port', min: 1, max: 65535, def: 3306 }),
    database: v.str(b.database, { name: 'Database name', required: true, max: 64, pattern: /^[A-Za-z0-9_]+$/ }),
    user: v.str(b.user, { name: 'Username', required: true, max: 80 }),
    password: v.str(b.password, { name: 'Password', max: 200, trim: false }),
  };
  let info;
  try {
    info = await db.testConnection(dbc, { createDatabase: true });
  } catch (err) {
    throw E.badRequest(`Could not connect: ${err.code || ''} ${String(err.message).replace(dbc.password || '\u0000', '***').slice(0, 200)}`);
  }
  const major = Number(String(info.version).split('.')[0]);
  const isMaria = /mariadb/i.test(info.version);
  if (!isMaria && major < 8) throw E.badRequest(`MySQL 8+ is required (found ${info.version})`);
  const existing = fs.existsSync(paths.ENV_FILE) ? require('dotenv').parse(fs.readFileSync(paths.ENV_FILE)) : {};
  writeEnv({
    NODE_ENV: existing.NODE_ENV || 'production',
    PORT: existing.PORT || String(config.port),
    APP_URL: existing.APP_URL || `${req.protocol}://${req.get('host')}`,
    DB_HOST: dbc.host, DB_PORT: String(dbc.port), DB_NAME: dbc.database, DB_USER: dbc.user, DB_PASSWORD: dbc.password,
    SESSION_SECRET: existing.SESSION_SECRET || crypto.randomBytes(48).toString('hex'),
    ENCRYPTION_KEY: existing.ENCRYPTION_KEY || crypto.randomBytes(32).toString('hex'),
  });
  state.done.database = true;
  res.json({ ok: true, version: info.version, message: `Connected to ${info.version}` });
};

exports.tables = async (req, res) => {
  if (!state.done.database) throw E.badRequest('Configure the database first');
  await migrate(config.db);
  await db.init(config.db);
  await seed();
  const [{ n }] = await db.query("SELECT COUNT(*) AS n FROM information_schema.tables WHERE table_schema = DATABASE()");
  state.done.tables = true;
  res.json({ ok: true, tables: Number(n), message: `${n} tables ready` });
};

exports.admin = async (req, res) => {
  if (!state.done.tables) throw E.badRequest('Create the tables first');
  const name = v.str(req.body.name, { name: 'Name', min: 2, max: 120, required: true });
  const email = v.email(req.body.email);
  const password = v.password(req.body.password);
  const existing = await db.one('SELECT id FROM users WHERE email = ?', [email]);
  if (existing) {
    await db.run("UPDATE users SET name = ?, password_hash = ?, role = 'admin', status = 'active', email_verified_at = COALESCE(email_verified_at, UTC_TIMESTAMP()) WHERE id = ?",
      [name, await User.hashPassword(password), existing.id]);
  } else {
    await User.create({ name, email, password, role: 'admin', verified: true });
  }
  state.done.admin = true;
  res.json({ ok: true, message: 'Administrator account ready' });
};

exports.site = async (req, res) => {
  if (!state.done.tables) throw E.badRequest('Create the tables first');
  const out = {};
  if (req.body.site_name !== undefined) out.site_name = v.str(req.body.site_name, { name: 'Site name', required: true, max: 80 });
  if (req.body.site_subtitle !== undefined) out.site_subtitle = v.str(req.body.site_subtitle, { name: 'Subtitle', max: 80 });
  if (req.body.default_timezone) {
    try { Intl.DateTimeFormat('en', { timeZone: req.body.default_timezone }); out.default_timezone = req.body.default_timezone; } catch { throw E.badRequest('Unknown timezone'); }
  }
  if (req.body.primary_color) out.primary_color = v.color(req.body.primary_color, '#2563eb');
  if (req.body.accent_color) out.accent_color = v.color(req.body.accent_color, '#7c3aed');
  if (out.site_name && !req.body.pwa_name) out.pwa_name = out.site_name;
  await settings.set(out);
  if (req.body.app_url) writeEnv({ APP_URL: v.url(req.body.app_url, { name: 'App URL', allowRelative: false }).replace(/\/+$/, '') });
  res.json({ ok: true, message: 'Saved' });
};

exports.logo = async (req, res) => {
  if (!state.done.tables) throw E.badRequest('Create the tables first');
  const saved = await fileStorage.saveImage(req.file, { purpose: 'brand_logo', visibility: 'public', maxWidth: 512 });
  const icon = await fileStorage.saveImage(req.file, { purpose: 'brand_pwa_icon', visibility: 'public', square: 512 });
  await settings.set({ logo_url: saved.url, pwa_icon_url: icon.url });
  res.json({ ok: true, url: saved.url, message: 'Logo uploaded' });
};

exports.smtp = async (req, res) => {
  if (!state.done.tables) throw E.badRequest('Create the tables first');
  const b = req.body;
  if (v.bool(b.skip)) return res.json({ ok: true, message: 'SMTP skipped — emails will be written to logs/mail.log' });
  await db.run('INSERT IGNORE INTO smtp_settings (id) VALUES (1)');
  await db.run('UPDATE smtp_settings SET host = ?, port = ?, username = ?, password_encrypted = ?, encryption = ?, from_name = ?, from_email = ?, enabled = 1 WHERE id = 1', [
    v.str(b.host, { name: 'SMTP host', required: true, max: 190, pattern: /^[\w.-]+$/ }),
    v.int(b.port, { name: 'Port', min: 1, max: 65535, def: 587 }),
    v.str(b.username, { max: 190 }) || null,
    b.password ? encrypt(String(b.password)) : null,
    v.oneOf(b.encryption, ['none', 'ssl', 'tls'], { def: 'tls' }),
    v.str(b.from_name, { max: 120 }) || null,
    v.email(b.from_email, { required: false }) || null,
  ]);
  res.json({ ok: true, message: 'SMTP saved' });
};

exports.pwa = async (req, res) => {
  if (!state.done.tables) throw E.badRequest('Create the tables first');
  await settings.set({
    pwa_name: v.str(req.body.pwa_name, { name: 'App name', required: true, max: 80 }),
    pwa_short_name: v.str(req.body.pwa_short_name, { name: 'Short name', required: true, max: 30 }),
    pwa_theme_color: v.color(req.body.pwa_theme_color, '#2563eb'),
    pwa_background_color: v.color(req.body.pwa_background_color, '#ffffff'),
  });
  res.json({ ok: true, message: 'PWA settings saved' });
};

exports.finish = (onInstalled) => async (req, res) => {
  if (!state.done.tables || !state.done.admin) throw E.badRequest('Complete the database and admin steps first');
  fs.writeFileSync(paths.INSTALL_LOCK, JSON.stringify({ installed_at: new Date().toISOString(), version: require('../../package.json').version }), { mode: 0o644 });
  state.key = null;
  res.clearCookie(COOKIE, { path: '/install' });
  await onInstalled();
  res.json({ ok: true, redirect: '/login', message: 'Installation complete!' });
};
