<?php
/**
 * One-click web installer.
 * Opens automatically the first time the domain is visited (no config.php yet).
 */
declare(strict_types=1);

require dirname(__DIR__) . '/includes/bootstrap.php';
require ROOT . '/includes/schema.php';

// Used by the browser to detect whether .htaccess rewrites work.
if (isset($_GET['rwtest'])) {
    header('Content-Type: text/plain');
    exit('OK-REWRITE');
}

$base = rtrim(str_replace('\\', '/', dirname(dirname($_SERVER['SCRIPT_NAME'] ?? '/install/index.php'))), '/') . '/';

$checks = [
    ['PHP 7.4 or newer (you have ' . PHP_VERSION . ')', version_compare(PHP_VERSION, '7.4.0', '>='), true],
    ['PDO extension', extension_loaded('pdo'), true],
    ['PDO MySQL driver', extension_loaded('pdo_mysql'), false],
    ['PDO SQLite driver', extension_loaded('pdo_sqlite'), false],
    ['mbstring extension', extension_loaded('mbstring'), true],
    ['Site folder is writable (to create config.php)', is_writable(ROOT), true],
    ['data/ folder is writable (cache & SQLite)', is_dir(ROOT . '/data') && is_writable(ROOT . '/data'), true],
];
$driversOk = extension_loaded('pdo_mysql') || extension_loaded('pdo_sqlite');
$ready = $driversOk;
foreach ($checks as $c) {
    if ($c[2] && !$c[1]) {
        $ready = false;
    }
}

$errors = [];
$done = false;
$old = [
    'driver' => extension_loaded('pdo_mysql') ? 'mysql' : 'sqlite',
    'db_host' => 'localhost', 'db_port' => '3306', 'db_name' => '', 'db_user' => '', 'db_pass' => '',
    'site_name' => 'CodeNexa', 'site_email' => '', 'admin_name' => 'Admin', 'admin_email' => '', 'admin_pass' => '',
    'pretty' => '1', 'demo' => '1',
];

if (!is_installed() && $_SERVER['REQUEST_METHOD'] === 'POST') {
    foreach ($old as $k => $v) {
        $old[$k] = trim((string) ($_POST[$k] ?? ($k === 'pretty' || $k === 'demo' ? '0' : '')));
    }
    $old['db_pass'] = (string) ($_POST['db_pass'] ?? '');
    $old['admin_pass'] = (string) ($_POST['admin_pass'] ?? '');

    if (!csrf_check()) {
        $errors[] = 'Session expired. Please submit the form again.';
    }
    if (!$ready) {
        $errors[] = 'Please fix the server requirements first.';
    }
    if (!in_array($old['driver'], ['mysql', 'sqlite'], true)) {
        $errors[] = 'Choose a database type.';
    }
    if ($old['driver'] === 'mysql' && ($old['db_name'] === '' || $old['db_user'] === '')) {
        $errors[] = 'Database name and username are required for MySQL.';
    }
    if ($old['driver'] === 'mysql' && !preg_match('/^[A-Za-z0-9_$-]+$/', $old['db_name'])) {
        $errors[] = 'Database name may only contain letters, numbers, _ $ and -.';
    }
    if ($old['site_name'] === '') {
        $errors[] = 'Site name is required.';
    }
    if (!filter_var($old['admin_email'], FILTER_VALIDATE_EMAIL)) {
        $errors[] = 'A valid admin email is required.';
    }
    if (strlen($old['admin_pass']) < 8) {
        $errors[] = 'Admin password must be at least 8 characters.';
    }

    if (!$errors) {
        try {
            if ($old['driver'] === 'sqlite') {
                $dbCfg = ['driver' => 'sqlite', 'path' => 'data/site-' . bin2hex(random_bytes(8)) . '.sqlite'];
                $pdo = make_pdo($dbCfg);
            } else {
                $dbCfg = [
                    'driver' => 'mysql', 'host' => $old['db_host'] ?: 'localhost', 'port' => (int) ($old['db_port'] ?: 3306),
                    'name' => $old['db_name'], 'user' => $old['db_user'], 'pass' => $old['db_pass'],
                ];
                try {
                    $pdo = make_pdo($dbCfg);
                } catch (PDOException $ex) {
                    // Unknown database → try to create it (works when the user has the privilege).
                    if (strpos($ex->getMessage(), '1049') === false) {
                        throw $ex;
                    }
                    $tmp = make_pdo(['name' => ''] + $dbCfg);
                    $tmp->exec('CREATE DATABASE `' . $dbCfg['name'] . '` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
                    $pdo = make_pdo($dbCfg);
                }
            }

            schema_install($pdo, $dbCfg['driver'], [
                'name' => $old['site_name'],
                'email' => $old['site_email'] ?: $old['admin_email'],
                'admin_name' => $old['admin_name'] ?: 'Admin',
                'admin_email' => strtolower($old['admin_email']),
                'admin_pass' => $old['admin_pass'],
            ], $old['demo'] === '1');

            $config = [
                'db' => $dbCfg,
                'base' => $base,
                'pretty' => $old['pretty'] === '1',
                'cache' => true,
                'installed_at' => date('c'),
            ];
            $php = "<?php\n// Generated by the installer on " . date('Y-m-d H:i') . ". Delete this file to re-run the installer.\nreturn " . var_export($config, true) . ";\n";
            if (@file_put_contents(CONFIG_FILE, $php, LOCK_EX) === false) {
                throw new RuntimeException('Could not write config.php. Make the site folder writable and try again.');
            }
            @chmod(CONFIG_FILE, 0640);
            if (!is_dir(CACHE_DIR)) {
                @mkdir(CACHE_DIR, 0755, true);
            }
            cache_clear();
            $done = true;
        } catch (Throwable $ex) {
            $errors[] = 'Installation failed: ' . $ex->getMessage();
        }
    }
}
$token = csrf_token();
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Install — CodeNexa</title>
<meta name="robots" content="noindex">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap">
<style>
:root{--a1:#6366f1;--a2:#3b82f6;--bg:#f6f7fb;--s:#fff;--t:#0f172a;--m:#5b6478;--b:#e3e7f0}
*{box-sizing:border-box}body{margin:0;font-family:Poppins,system-ui,sans-serif;background:var(--bg);color:var(--t);font-size:15px;line-height:1.6}
.wrap{width:min(760px,100% - 32px);margin:40px auto 60px}
.head{display:flex;align-items:center;gap:12px;margin-bottom:24px}.head h1{font-size:1.5rem;margin:0}
.head svg{width:42px;height:42px}
.card{background:var(--s);border:1px solid var(--b);border-radius:18px;padding:28px;box-shadow:0 10px 30px -14px rgba(15,23,42,.18);margin-bottom:20px;animation:in .5s cubic-bezier(.22,1,.36,1) both}
@keyframes in{from{opacity:0;transform:translateY(12px)}}
h2{font-size:1.05rem;margin:0 0 14px;display:flex;align-items:center;gap:10px}
h2 span{width:28px;height:28px;border-radius:50%;display:grid;place-items:center;color:#fff;font-size:.8rem;background:linear-gradient(135deg,var(--a1),var(--a2))}
ul.req{list-style:none;padding:0;margin:0;display:grid;gap:8px}
ul.req li{display:flex;justify-content:space-between;gap:12px;padding:10px 14px;border-radius:10px;background:var(--bg);font-size:.9rem}
.ok{color:#059669;font-weight:600}.no{color:#dc2626;font-weight:600}.opt{color:#d97706;font-weight:600}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.full{grid-column:1/-1}
label{display:block;font-size:.82rem;font-weight:500}
input[type=text],input[type=email],input[type=password],input[type=number]{width:100%;margin-top:6px;padding:11px 13px;border-radius:11px;border:1.5px solid var(--b);font:inherit;font-size:16px;outline:none;transition:border-color .2s,box-shadow .2s}
input:focus{border-color:var(--a1);box-shadow:0 0 0 4px rgba(99,102,241,.15)}
.seg{display:flex;gap:10px;flex-wrap:wrap}.seg label{flex:1;min-width:200px;border:1.5px solid var(--b);border-radius:12px;padding:12px 14px;cursor:pointer;display:flex;gap:10px;align-items:flex-start;transition:border-color .2s,background .2s}
.seg label:has(input:checked){border-color:var(--a1);background:rgba(99,102,241,.06)}
.seg small{display:block;color:var(--m);font-weight:400}
.check{display:flex;gap:10px;align-items:flex-start;font-size:.9rem;font-weight:400}.check small{color:var(--m);display:block}
.btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;height:50px;padding:0 28px;border:0;border-radius:999px;color:#fff;font:inherit;font-weight:600;cursor:pointer;background:linear-gradient(90deg,var(--a1),var(--a2));box-shadow:0 12px 24px -12px var(--a1);text-decoration:none;transition:transform .2s}
.btn:hover{transform:translateY(-2px)}.btn.ghost{background:none;color:var(--a1);box-shadow:none;border:1.5px solid var(--a1)}
.btn[disabled]{opacity:.6;pointer-events:none}
.alert{padding:14px 16px;border-radius:12px;margin-bottom:16px;font-size:.9rem}.alert.err{background:#fef2f2;color:#991b1b;border:1px solid #fecaca}.alert.ok{background:#ecfdf5;color:#065f46;border:1px solid #a7f3d0}
.muted{color:var(--m)}.mysql-only{transition:opacity .2s}.hidden{display:none}
.done{text-align:center}.done .big{font-size:3.4rem;line-height:1}
code{background:var(--bg);padding:2px 6px;border-radius:6px;font-size:.85em}
.row{display:flex;gap:12px;justify-content:center;flex-wrap:wrap;margin-top:18px}
@media(max-width:620px){.grid{grid-template-columns:1fr}.card{padding:20px}}
</style>
</head>
<body>
<div class="wrap">
    <div class="head">
        <svg viewBox="0 0 48 48"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#6366f1"/><stop offset="1" stop-color="#3b82f6"/></linearGradient></defs><path d="M24 3 42 13.5v21L24 45 6 34.5v-21Z" fill="none" stroke="url(#g)" stroke-width="4" stroke-linejoin="round"/><path d="m19 18-6 6 6 6M29 18l6 6-6 6M26 15l-4 18" fill="none" stroke="url(#g)" stroke-width="3.2" stroke-linecap="round" stroke-linejoin="round"/></svg>
        <div><h1>Website Installer</h1><div class="muted">Set up your site in under a minute.</div></div>
    </div>

<?php if ($done): ?>
    <div class="card done">
        <div class="big">🎉</div>
        <h2 style="justify-content:center">Installation complete!</h2>
        <p class="muted">Your website and admin panel are ready.</p>
        <div class="alert ok">For security, delete the <code>install/</code> folder from your server now.</div>
        <div class="row">
            <a class="btn" href="<?= e($base) ?>">Open Website</a>
            <a class="btn ghost" href="<?= e($base) ?>admin/">Open Admin Panel</a>
        </div>
    </div>
<?php elseif (is_installed()): ?>
    <div class="card done">
        <div class="big">✅</div>
        <h2 style="justify-content:center">Already installed</h2>
        <p class="muted">To reinstall, delete <code>config.php</code> from the site folder and reload this page.<br>For security, you should delete the <code>install/</code> folder.</p>
        <div class="row"><a class="btn" href="<?= e($base) ?>">Open Website</a><a class="btn ghost" href="<?= e($base) ?>admin/">Admin Panel</a></div>
    </div>
<?php else: ?>
    <?php if ($errors): ?>
        <div class="alert err"><?php foreach ($errors as $er): ?><div>• <?= e($er) ?></div><?php endforeach; ?></div>
    <?php endif; ?>

    <div class="card">
        <h2><span>1</span> Server requirements</h2>
        <ul class="req">
            <?php foreach ($checks as $c): ?>
                <li><span><?= e($c[0]) ?><?= $c[2] ? '' : ' <small class="muted">(one DB driver needed)</small>' ?></span>
                    <span class="<?= $c[1] ? 'ok' : ($c[2] ? 'no' : 'opt') ?>"><?= $c[1] ? '✓ OK' : ($c[2] ? '✗ Missing' : '— Not available') ?></span></li>
            <?php endforeach; ?>
        </ul>
        <?php if (!$ready): ?><p class="no" style="margin-top:14px">Fix the items marked ✗ (ask your hosting provider), then reload this page.</p><?php endif; ?>
    </div>

    <form method="post" autocomplete="off">
        <input type="hidden" name="_csrf" value="<?= e($token) ?>">
        <div class="card">
            <h2><span>2</span> Database</h2>
            <div class="seg" style="margin-bottom:16px">
                <label><input type="radio" name="driver" value="mysql" <?= $old['driver'] === 'mysql' ? 'checked' : '' ?> <?= extension_loaded('pdo_mysql') ? '' : 'disabled' ?>>
                    <span><strong>MySQL / MariaDB</strong><small>Recommended for cPanel &amp; shared hosting</small></span></label>
                <label><input type="radio" name="driver" value="sqlite" <?= $old['driver'] === 'sqlite' ? 'checked' : '' ?> <?= extension_loaded('pdo_sqlite') ? '' : 'disabled' ?>>
                    <span><strong>SQLite</strong><small>No database setup needed</small></span></label>
            </div>
            <div class="grid mysql-only" id="mysqlFields">
                <label>Database host<input type="text" name="db_host" value="<?= e($old['db_host']) ?>"></label>
                <label>Port<input type="number" name="db_port" value="<?= e($old['db_port']) ?>"></label>
                <label>Database name<input type="text" name="db_name" value="<?= e($old['db_name']) ?>" placeholder="e.g. cpuser_codenexa"></label>
                <label>Database username<input type="text" name="db_user" value="<?= e($old['db_user']) ?>"></label>
                <label class="full">Database password<input type="password" name="db_pass" value="<?= e($old['db_pass']) ?>" autocomplete="new-password"></label>
                <p class="muted full" style="margin:0;font-size:.85rem">cPanel: create the database &amp; user in <em>MySQL® Databases</em> and add the user to the database with ALL PRIVILEGES.</p>
            </div>
        </div>

        <div class="card">
            <h2><span>3</span> Website &amp; admin account</h2>
            <div class="grid">
                <label>Site name<input type="text" name="site_name" value="<?= e($old['site_name']) ?>" required></label>
                <label>Contact email (shown on site)<input type="email" name="site_email" value="<?= e($old['site_email']) ?>" placeholder="hello@yourdomain.com"></label>
                <label>Admin name<input type="text" name="admin_name" value="<?= e($old['admin_name']) ?>"></label>
                <label>Admin login email<input type="email" name="admin_email" value="<?= e($old['admin_email']) ?>" required></label>
                <label class="full">Admin password (min 8 characters)<input type="password" name="admin_pass" minlength="8" required autocomplete="new-password"></label>
                <label class="check full"><input type="checkbox" name="demo" value="1" <?= $old['demo'] === '1' ? 'checked' : '' ?>>
                    <span>Load demo content<small>Services, projects, pricing and team — edit or delete later in the admin panel.</small></span></label>
                <label class="check full"><input type="checkbox" name="pretty" value="1" id="pretty" <?= $old['pretty'] === '1' ? 'checked' : '' ?>>
                    <span>SEO-friendly URLs (<code>/services</code>)<small id="rwStatus">Checking server support…</small></span></label>
            </div>
        </div>

        <button class="btn" type="submit" style="width:100%" <?= $ready ? '' : 'disabled' ?>>Install Now →</button>
    </form>
    <script>
    (function () {
        var radios = document.querySelectorAll('input[name=driver]'), box = document.getElementById('mysqlFields');
        function sync() { var m = document.querySelector('input[name=driver]:checked'); box.classList.toggle('hidden', !m || m.value !== 'mysql'); }
        radios.forEach(function (r) { r.addEventListener('change', sync); }); sync();
        var st = document.getElementById('rwStatus'), cb = document.getElementById('pretty');
        fetch(<?= json_encode($base . 'install-rewrite-test') ?>, { cache: 'no-store' })
            .then(function (r) { return r.text(); })
            .then(function (t) {
                if (t.trim() === 'OK-REWRITE') { st.textContent = '✓ Supported by your server.'; }
                else { throw 0; }
            })
            .catch(function () { cb.checked = false; st.textContent = 'Not detected (mod_rewrite off or Nginx). Links will use ?p=page instead.'; });
        document.querySelector('form').addEventListener('submit', function () {
            var b = this.querySelector('button[type=submit]'); b.textContent = 'Installing…'; b.setAttribute('disabled', '');
        });
    })();
    </script>
<?php endif; ?>
</div>
</body>
</html>
