import { sql, type Kysely } from 'kysely';

/**
 * Initial schema. Migrations are forward-only in production: an update ships
 * NEW migration files and never drops or recreates existing tables.
 */
const T = 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci';
const NOW = 'DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)';
const UPD = 'DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)';
const MONEY = 'DECIMAL(12,2)';

const blockList = (name: string, len: number) => `
CREATE TABLE IF NOT EXISTS ${name} (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  value VARCHAR(${len}) NOT NULL,
  reason VARCHAR(500) NULL,
  attempts INT NOT NULL DEFAULT 0,
  expires_at DATETIME(3) NULL,
  created_by INT UNSIGNED NULL,
  created_at ${NOW},
  updated_at ${UPD},
  UNIQUE KEY uq_${name}_value (value),
  KEY idx_${name}_expires (expires_at)
) ${T}`;

export const statements: string[] = [
  `CREATE TABLE IF NOT EXISTS installation (
    id TINYINT UNSIGNED PRIMARY KEY,
    installation_id CHAR(36) NOT NULL,
    status VARCHAR(20) NOT NULL,
    version VARCHAR(20) NOT NULL,
    site_url VARCHAR(255) NOT NULL,
    installed_at DATETIME(3) NOT NULL
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS system_settings (
    \`key\` VARCHAR(120) PRIMARY KEY,
    value LONGTEXT NULL,
    updated_at ${UPD}
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS site_settings (
    \`key\` VARCHAR(120) PRIMARY KEY,
    \`group\` VARCHAR(40) NOT NULL,
    value LONGTEXT NULL,
    is_secret TINYINT(1) NOT NULL DEFAULT 0,
    updated_at ${UPD},
    KEY idx_site_settings_group (\`group\`)
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS seo_settings (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    page_key VARCHAR(60) NOT NULL,
    title VARCHAR(255) NULL,
    description VARCHAR(500) NULL,
    keywords VARCHAR(500) NULL,
    og_image VARCHAR(255) NULL,
    updated_at ${UPD},
    UNIQUE KEY uq_seo_page (page_key)
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS roles (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    slug VARCHAR(80) NOT NULL,
    is_system TINYINT(1) NOT NULL DEFAULT 0,
    created_at ${NOW},
    UNIQUE KEY uq_roles_slug (slug)
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS permissions (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(80) NOT NULL,
    name VARCHAR(120) NOT NULL,
    \`group\` VARCHAR(40) NOT NULL,
    UNIQUE KEY uq_permissions_slug (slug)
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS role_permissions (
    role_id INT UNSIGNED NOT NULL,
    permission_id INT UNSIGNED NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_rp_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT fk_rp_perm FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS admins (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    role_id INT UNSIGNED NOT NULL,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL,
    phone VARCHAR(30) NULL,
    password_hash VARCHAR(255) NOT NULL,
    totp_secret VARCHAR(255) NULL,
    totp_enabled TINYINT(1) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    failed_attempts INT NOT NULL DEFAULT 0,
    locked_until DATETIME(3) NULL,
    last_login_at DATETIME(3) NULL,
    last_login_ip VARCHAR(64) NULL,
    created_at ${NOW},
    updated_at ${UPD},
    UNIQUE KEY uq_admins_email (email),
    CONSTRAINT fk_admins_role FOREIGN KEY (role_id) REFERENCES roles(id)
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS admin_sessions (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    admin_id INT UNSIGNED NOT NULL,
    token_hash CHAR(64) NOT NULL,
    ip VARCHAR(64) NULL,
    user_agent VARCHAR(500) NULL,
    mfa_pending TINYINT(1) NOT NULL DEFAULT 0,
    auth_method VARCHAR(20) NOT NULL DEFAULT 'password',
    created_at ${NOW},
    last_seen_at DATETIME(3) NOT NULL,
    expires_at DATETIME(3) NOT NULL,
    revoked_at DATETIME(3) NULL,
    UNIQUE KEY uq_sessions_token (token_hash),
    KEY idx_sessions_admin (admin_id),
    CONSTRAINT fk_sessions_admin FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE CASCADE
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS admin_passkeys (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    admin_id INT UNSIGNED NOT NULL,
    credential_id VARCHAR(512) NOT NULL,
    public_key TEXT NOT NULL,
    counter BIGINT UNSIGNED NOT NULL DEFAULT 0,
    transports VARCHAR(255) NULL,
    device_type VARCHAR(40) NULL,
    backed_up TINYINT(1) NOT NULL DEFAULT 0,
    name VARCHAR(120) NOT NULL,
    created_at ${NOW},
    last_used_at DATETIME(3) NULL,
    UNIQUE KEY uq_passkeys_cred (credential_id(255)),
    KEY idx_passkeys_admin (admin_id),
    CONSTRAINT fk_passkeys_admin FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE CASCADE
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS customers (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    phone VARCHAR(20) NOT NULL,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NULL,
    district VARCHAR(80) NULL,
    upazila VARCHAR(80) NULL,
    address VARCHAR(500) NULL,
    total_orders INT NOT NULL DEFAULT 0,
    delivered_orders INT NOT NULL DEFAULT 0,
    cancelled_orders INT NOT NULL DEFAULT 0,
    returned_orders INT NOT NULL DEFAULT 0,
    total_spent ${MONEY} NOT NULL DEFAULT 0,
    is_blocked TINYINT(1) NOT NULL DEFAULT 0,
    notes VARCHAR(1000) NULL,
    first_order_at DATETIME(3) NULL,
    last_order_at DATETIME(3) NULL,
    created_at ${NOW},
    updated_at ${UPD},
    UNIQUE KEY uq_customers_phone (phone),
    KEY idx_customers_last_order (last_order_at)
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS addresses (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    customer_id INT UNSIGNED NOT NULL,
    name VARCHAR(120) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    district VARCHAR(80) NOT NULL,
    upazila VARCHAR(80) NOT NULL,
    address VARCHAR(500) NOT NULL,
    device_hash CHAR(64) NULL,
    last_used_at DATETIME(3) NOT NULL,
    KEY idx_addresses_customer (customer_id, last_used_at),
    KEY idx_addresses_address (address(120)),
    CONSTRAINT fk_addresses_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS categories (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    parent_id INT UNSIGNED NULL,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(160) NOT NULL,
    description VARCHAR(1000) NULL,
    icon_type VARCHAR(10) NOT NULL DEFAULT 'fa',
    icon_value VARCHAR(255) NULL,
    image VARCHAR(255) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    show_on_home TINYINT(1) NOT NULL DEFAULT 1,
    seo_title VARCHAR(255) NULL,
    seo_description VARCHAR(500) NULL,
    created_at ${NOW},
    updated_at ${UPD},
    deleted_at DATETIME(3) NULL,
    UNIQUE KEY uq_categories_slug (slug),
    KEY idx_categories_parent (parent_id),
    KEY idx_categories_active (is_active, deleted_at, sort_order),
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE SET NULL
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS brands (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(160) NOT NULL,
    logo VARCHAR(255) NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    created_at ${NOW},
    updated_at ${UPD},
    deleted_at DATETIME(3) NULL,
    UNIQUE KEY uq_brands_slug (slug)
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS products (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    category_id INT UNSIGNED NULL,
    subcategory_id INT UNSIGNED NULL,
    brand_id INT UNSIGNED NULL,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(280) NOT NULL,
    sku VARCHAR(80) NULL,
    price ${MONEY} NOT NULL,
    sale_price ${MONEY} NULL,
    cost_price ${MONEY} NULL,
    stock INT NOT NULL DEFAULT 0,
    low_stock_threshold INT NOT NULL DEFAULT 10,
    weight DECIMAL(10,3) NULL,
    short_description VARCHAR(1000) NULL,
    description MEDIUMTEXT NULL,
    specifications LONGTEXT NULL,
    has_variants TINYINT(1) NOT NULL DEFAULT 0,
    size_required TINYINT(1) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    is_featured TINYINT(1) NOT NULL DEFAULT 0,
    is_flash_sale TINYINT(1) NOT NULL DEFAULT 0,
    is_combo TINYINT(1) NOT NULL DEFAULT 0,
    free_delivery TINYINT(1) NOT NULL DEFAULT 0,
    cod_available TINYINT(1) NOT NULL DEFAULT 1,
    seo_title VARCHAR(255) NULL,
    seo_description VARCHAR(500) NULL,
    seo_keywords VARCHAR(500) NULL,
    meta_image VARCHAR(255) NULL,
    social_image VARCHAR(255) NULL,
    rating_avg DECIMAL(3,2) NOT NULL DEFAULT 0,
    rating_count INT NOT NULL DEFAULT 0,
    view_count INT NOT NULL DEFAULT 0,
    sold_count INT NOT NULL DEFAULT 0,
    created_at ${NOW},
    updated_at ${UPD},
    deleted_at DATETIME(3) NULL,
    UNIQUE KEY uq_products_slug (slug),
    UNIQUE KEY uq_products_sku (sku),
    KEY idx_products_listing (status, deleted_at, created_at),
    KEY idx_products_category (category_id, status, deleted_at),
    KEY idx_products_subcategory (subcategory_id),
    KEY idx_products_brand (brand_id),
    KEY idx_products_featured (is_featured, status),
    KEY idx_products_sold (sold_count),
    KEY idx_products_views (view_count),
    KEY idx_products_stock (stock, low_stock_threshold),
    FULLTEXT KEY ft_products_search (name, short_description, seo_keywords),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
    CONSTRAINT fk_products_subcategory FOREIGN KEY (subcategory_id) REFERENCES categories(id) ON DELETE SET NULL,
    CONSTRAINT fk_products_brand FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE SET NULL
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS product_images (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    product_id INT UNSIGNED NOT NULL,
    path VARCHAR(255) NOT NULL,
    width INT NULL,
    height INT NULL,
    alt VARCHAR(255) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_main TINYINT(1) NOT NULL DEFAULT 0,
    created_at ${NOW},
    KEY idx_product_images (product_id, sort_order),
    CONSTRAINT fk_product_images_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS product_variants (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    product_id INT UNSIGNED NOT NULL,
    sku VARCHAR(80) NULL,
    size VARCHAR(40) NULL,
    color VARCHAR(60) NULL,
    color_hex VARCHAR(9) NULL,
    price ${MONEY} NULL,
    sale_price ${MONEY} NULL,
    stock INT NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    KEY idx_variants_product (product_id, sort_order),
    CONSTRAINT fk_variants_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS product_reviews (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    product_id INT UNSIGNED NOT NULL,
    customer_name VARCHAR(120) NOT NULL,
    phone VARCHAR(20) NULL,
    rating TINYINT UNSIGNED NOT NULL,
    comment VARCHAR(2000) NULL,
    is_approved TINYINT(1) NOT NULL DEFAULT 0,
    created_at ${NOW},
    KEY idx_reviews_product (product_id, is_approved, created_at),
    CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS order_statuses (
    code VARCHAR(30) PRIMARY KEY,
    label VARCHAR(60) NOT NULL,
    label_bn VARCHAR(60) NULL,
    color VARCHAR(20) NOT NULL,
    sort_order INT NOT NULL,
    is_final TINYINT(1) NOT NULL DEFAULT 0
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS couriers (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(80) NOT NULL,
    driver VARCHAR(40) NOT NULL,
    is_enabled TINYINT(1) NOT NULL DEFAULT 0,
    is_default TINYINT(1) NOT NULL DEFAULT 0,
    created_at ${NOW},
    updated_at ${UPD},
    UNIQUE KEY uq_couriers_code (code)
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS coupons (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(40) NOT NULL,
    description VARCHAR(255) NULL,
    type VARCHAR(10) NOT NULL,
    value ${MONEY} NOT NULL,
    min_order ${MONEY} NOT NULL DEFAULT 0,
    max_discount ${MONEY} NULL,
    starts_at DATETIME(3) NULL,
    expires_at DATETIME(3) NULL,
    usage_limit INT NULL,
    per_customer_limit INT NULL,
    used_count INT NOT NULL DEFAULT 0,
    applies_to VARCHAR(12) NOT NULL DEFAULT 'all',
    product_ids LONGTEXT NULL,
    category_ids LONGTEXT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    highlight_on_home TINYINT(1) NOT NULL DEFAULT 0,
    created_at ${NOW},
    updated_at ${UPD},
    deleted_at DATETIME(3) NULL,
    UNIQUE KEY uq_coupons_code (code)
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS orders (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    order_no VARCHAR(24) NOT NULL,
    public_token CHAR(43) NOT NULL,
    customer_id INT UNSIGNED NULL,
    customer_name VARCHAR(120) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    district VARCHAR(80) NOT NULL,
    upazila VARCHAR(80) NOT NULL,
    address VARCHAR(500) NOT NULL,
    note VARCHAR(1000) NULL,
    status VARCHAR(30) NOT NULL,
    payment_method VARCHAR(20) NOT NULL DEFAULT 'cod',
    subtotal ${MONEY} NOT NULL,
    discount ${MONEY} NOT NULL DEFAULT 0,
    delivery_charge ${MONEY} NOT NULL DEFAULT 0,
    total ${MONEY} NOT NULL,
    coupon_id INT UNSIGNED NULL,
    coupon_code VARCHAR(40) NULL,
    item_count INT NOT NULL,
    ip VARCHAR(64) NULL,
    ip_location VARCHAR(255) NULL,
    device_hash CHAR(64) NULL,
    user_agent VARCHAR(500) NULL,
    device_info LONGTEXT NULL,
    risk_score INT NOT NULL DEFAULT 0,
    risk_level VARCHAR(10) NOT NULL DEFAULT 'LOW',
    risk_reasons LONGTEXT NULL,
    courier_id INT UNSIGNED NULL,
    consignment_id VARCHAR(80) NULL,
    tracking_code VARCHAR(120) NULL,
    courier_status VARCHAR(60) NULL,
    admin_note VARCHAR(1000) NULL,
    source VARCHAR(40) NULL,
    confirmed_at DATETIME(3) NULL,
    delivered_at DATETIME(3) NULL,
    cancelled_at DATETIME(3) NULL,
    created_at ${NOW},
    updated_at ${UPD},
    deleted_at DATETIME(3) NULL,
    UNIQUE KEY uq_orders_no (order_no),
    KEY idx_orders_status (status, deleted_at, created_at),
    KEY idx_orders_created (created_at),
    KEY idx_orders_phone (phone, created_at),
    KEY idx_orders_ip (ip, created_at),
    KEY idx_orders_device (device_hash, created_at),
    KEY idx_orders_customer (customer_id),
    KEY idx_orders_courier (courier_id, status),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
    CONSTRAINT fk_orders_status FOREIGN KEY (status) REFERENCES order_statuses(code),
    CONSTRAINT fk_orders_coupon FOREIGN KEY (coupon_id) REFERENCES coupons(id) ON DELETE SET NULL,
    CONSTRAINT fk_orders_courier FOREIGN KEY (courier_id) REFERENCES couriers(id) ON DELETE SET NULL
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS combo_offers (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    slug VARCHAR(220) NOT NULL,
    description VARCHAR(2000) NULL,
    image VARCHAR(255) NULL,
    price ${MONEY} NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    starts_at DATETIME(3) NULL,
    ends_at DATETIME(3) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at ${NOW},
    updated_at ${UPD},
    deleted_at DATETIME(3) NULL,
    UNIQUE KEY uq_combos_slug (slug)
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS combo_items (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    combo_id INT UNSIGNED NOT NULL,
    product_id INT UNSIGNED NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    KEY idx_combo_items (combo_id),
    CONSTRAINT fk_combo_items_combo FOREIGN KEY (combo_id) REFERENCES combo_offers(id) ON DELETE CASCADE,
    CONSTRAINT fk_combo_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS order_items (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    order_id INT UNSIGNED NOT NULL,
    product_id INT UNSIGNED NULL,
    variant_id INT UNSIGNED NULL,
    combo_id INT UNSIGNED NULL,
    name VARCHAR(255) NOT NULL,
    sku VARCHAR(80) NULL,
    size VARCHAR(40) NULL,
    color VARCHAR(60) NULL,
    image VARCHAR(255) NULL,
    unit_price ${MONEY} NOT NULL,
    cost_price ${MONEY} NULL,
    quantity INT NOT NULL,
    line_total ${MONEY} NOT NULL,
    KEY idx_order_items_order (order_id),
    KEY idx_order_items_product (product_id),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
    CONSTRAINT fk_order_items_variant FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE SET NULL,
    CONSTRAINT fk_order_items_combo FOREIGN KEY (combo_id) REFERENCES combo_offers(id) ON DELETE SET NULL
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS order_status_history (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    order_id INT UNSIGNED NOT NULL,
    from_status VARCHAR(30) NULL,
    to_status VARCHAR(30) NOT NULL,
    note VARCHAR(500) NULL,
    admin_id INT UNSIGNED NULL,
    created_at ${NOW},
    KEY idx_osh_order (order_id, created_at),
    CONSTRAINT fk_osh_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_osh_admin FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE SET NULL
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS coupon_usage (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    coupon_id INT UNSIGNED NOT NULL,
    order_id INT UNSIGNED NOT NULL,
    phone VARCHAR(20) NOT NULL,
    discount ${MONEY} NOT NULL,
    created_at ${NOW},
    KEY idx_coupon_usage (coupon_id, phone),
    CONSTRAINT fk_cu_coupon FOREIGN KEY (coupon_id) REFERENCES coupons(id) ON DELETE CASCADE,
    CONSTRAINT fk_cu_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS banners (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(160) NULL,
    subtitle VARCHAR(255) NULL,
    button_text VARCHAR(40) NULL,
    image VARCHAR(255) NOT NULL,
    mobile_image VARCHAR(255) NULL,
    link_type VARCHAR(12) NOT NULL DEFAULT 'none',
    link_value VARCHAR(500) NULL,
    starts_at DATETIME(3) NULL,
    ends_at DATETIME(3) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at ${NOW},
    updated_at ${UPD},
    deleted_at DATETIME(3) NULL,
    KEY idx_banners_active (is_active, deleted_at, sort_order)
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS flash_sales (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(160) NOT NULL,
    starts_at DATETIME(3) NOT NULL,
    ends_at DATETIME(3) NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at ${NOW},
    updated_at ${UPD},
    KEY idx_flash_window (is_active, starts_at, ends_at)
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS flash_sale_items (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    flash_sale_id INT UNSIGNED NOT NULL,
    product_id INT UNSIGNED NOT NULL,
    sale_price ${MONEY} NOT NULL,
    stock_limit INT NULL,
    sold_count INT NOT NULL DEFAULT 0,
    UNIQUE KEY uq_flash_item (flash_sale_id, product_id),
    KEY idx_flash_product (product_id),
    CONSTRAINT fk_fsi_sale FOREIGN KEY (flash_sale_id) REFERENCES flash_sales(id) ON DELETE CASCADE,
    CONSTRAINT fk_fsi_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS home_sections (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    section_key VARCHAR(40) NOT NULL,
    title VARCHAR(120) NOT NULL,
    subtitle VARCHAR(255) NULL,
    is_enabled TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    product_limit INT NOT NULL DEFAULT 8,
    grid_columns INT NOT NULL DEFAULT 2,
    per_page INT NOT NULL DEFAULT 8,
    config LONGTEXT NULL,
    UNIQUE KEY uq_home_sections_key (section_key)
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS delivery_rules (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    type VARCHAR(20) NOT NULL,
    district VARCHAR(80) NULL,
    charge ${MONEY} NOT NULL DEFAULT 0,
    min_order ${MONEY} NULL,
    priority INT NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at ${NOW},
    updated_at ${UPD},
    KEY idx_delivery_rules (is_active, type, priority)
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS courier_credentials (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    courier_id INT UNSIGNED NOT NULL,
    credentials TEXT NOT NULL,
    updated_at ${UPD},
    UNIQUE KEY uq_courier_credentials (courier_id),
    CONSTRAINT fk_cc_courier FOREIGN KEY (courier_id) REFERENCES couriers(id) ON DELETE CASCADE
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS courier_shipments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    order_id INT UNSIGNED NOT NULL,
    courier_id INT UNSIGNED NOT NULL,
    consignment_id VARCHAR(80) NULL,
    tracking_code VARCHAR(120) NULL,
    status VARCHAR(60) NOT NULL,
    cod_amount ${MONEY} NOT NULL,
    request_payload LONGTEXT NULL,
    response_payload LONGTEXT NULL,
    error VARCHAR(1000) NULL,
    created_at ${NOW},
    updated_at ${UPD},
    KEY idx_shipments_order (order_id),
    KEY idx_shipments_courier (courier_id, status),
    CONSTRAINT fk_shipments_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_shipments_courier FOREIGN KEY (courier_id) REFERENCES couriers(id)
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS fraud_events (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(40) NOT NULL,
    ip VARCHAR(64) NULL,
    phone VARCHAR(20) NULL,
    device_hash CHAR(64) NULL,
    order_id INT UNSIGNED NULL,
    risk_score INT NOT NULL DEFAULT 0,
    risk_level VARCHAR(10) NOT NULL,
    reasons LONGTEXT NULL,
    action VARCHAR(20) NOT NULL,
    created_at ${NOW},
    KEY idx_fraud_created (created_at),
    KEY idx_fraud_ip (ip, created_at),
    KEY idx_fraud_phone (phone),
    CONSTRAINT fk_fraud_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL
  ) ${T}`,
  blockList('blocked_ips', 64),
  blockList('blocked_devices', 64),
  blockList('blocked_phones', 20),
  `CREATE TABLE IF NOT EXISTS analytics_events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    event VARCHAR(40) NOT NULL,
    session_id VARCHAR(64) NULL,
    device_hash CHAR(64) NULL,
    product_id INT UNSIGNED NULL,
    category_id INT UNSIGNED NULL,
    value ${MONEY} NULL,
    meta LONGTEXT NULL,
    ip VARCHAR(64) NULL,
    created_at ${NOW},
    KEY idx_analytics_event (event, created_at),
    KEY idx_analytics_product (product_id, event),
    KEY idx_analytics_created (created_at)
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS notifications (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(40) NOT NULL,
    title VARCHAR(200) NOT NULL,
    message VARCHAR(1000) NULL,
    link VARCHAR(255) NULL,
    data LONGTEXT NULL,
    is_read TINYINT(1) NOT NULL DEFAULT 0,
    created_at ${NOW},
    KEY idx_notifications (is_read, created_at)
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    admin_id INT UNSIGNED NULL,
    admin_name VARCHAR(120) NULL,
    action VARCHAR(80) NOT NULL,
    target_type VARCHAR(40) NULL,
    target_id VARCHAR(40) NULL,
    old_value LONGTEXT NULL,
    new_value LONGTEXT NULL,
    ip VARCHAR(64) NULL,
    user_agent VARCHAR(500) NULL,
    created_at ${NOW},
    KEY idx_audit_created (created_at),
    KEY idx_audit_target (target_type, target_id),
    KEY idx_audit_admin (admin_id)
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS trash (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    entity_type VARCHAR(30) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    snapshot LONGTEXT NULL,
    deleted_by INT UNSIGNED NULL,
    deleted_at ${NOW},
    UNIQUE KEY uq_trash_entity (entity_type, entity_id)
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS pages (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(120) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content MEDIUMTEXT NULL,
    seo_title VARCHAR(255) NULL,
    seo_description VARCHAR(500) NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    show_in_footer TINYINT(1) NOT NULL DEFAULT 1,
    created_at ${NOW},
    updated_at ${UPD},
    UNIQUE KEY uq_pages_slug (slug)
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS update_history (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    from_version VARCHAR(20) NOT NULL,
    to_version VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    log MEDIUMTEXT NULL,
    backup_file VARCHAR(255) NULL,
    admin_id INT UNSIGNED NULL,
    started_at ${NOW},
    finished_at DATETIME(3) NULL
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS backups (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    file VARCHAR(255) NOT NULL,
    size BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    note VARCHAR(500) NULL,
    created_by INT UNSIGNED NULL,
    created_at ${NOW}
  ) ${T}`,
  `CREATE TABLE IF NOT EXISTS media (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    path VARCHAR(255) NOT NULL,
    folder VARCHAR(40) NOT NULL,
    original_name VARCHAR(255) NULL,
    mime VARCHAR(60) NULL,
    size INT NULL,
    width INT NULL,
    height INT NULL,
    created_at ${NOW},
    KEY idx_media_folder (folder, created_at)
  ) ${T}`,
];

export async function up(db: Kysely<any>): Promise<void> {
  for (const statement of statements) {
    await sql.raw(statement).execute(db);
  }
}
