import fs from 'node:fs';
import { ENV_FILE } from './paths.js';

/** Minimal dotenv parser/writer — keeps the dependency surface small. */
export function parseEnv(content: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const raw of content.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1).replace(/\\n/g, '\n').replace(/\\"/g, '"').replace(/\\\\/g, '\\');
    }
    out[key] = value;
  }
  return out;
}

export function loadEnvFile(): void {
  if (!fs.existsSync(ENV_FILE)) return;
  const parsed = parseEnv(fs.readFileSync(ENV_FILE, 'utf8'));
  for (const [k, v] of Object.entries(parsed)) {
    // Real environment variables (hosting panel) win over the file.
    if (process.env[k] === undefined) process.env[k] = v;
  }
}

function quote(value: string): string {
  if (/^[A-Za-z0-9_./:@+-]*$/.test(value)) return value;
  return '"' + value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n') + '"';
}

const ENV_KEY = /^[A-Z][A-Z0-9_]{0,63}$/;

/** Writes (or merges into) the shared .env with 0600 permissions, atomically. */
export function writeEnvFile(values: Record<string, string>, header = 'ShopiGo environment — generated by the installer. Keep this file private.'): void {
  const existing = fs.existsSync(ENV_FILE) ? parseEnv(fs.readFileSync(ENV_FILE, 'utf8')) : {};
  const merged = { ...existing, ...values };
  const lines = [`# ${header}`, `# Updated ${new Date().toISOString()}`];
  for (const [k, v] of Object.entries(merged)) {
    if (!ENV_KEY.test(k)) throw new Error(`Invalid env key: ${k}`);
    lines.push(`${k}=${quote(v)}`);
  }
  const tmp = ENV_FILE + '.tmp';
  fs.writeFileSync(tmp, lines.join('\n') + '\n', { mode: 0o600 });
  fs.renameSync(tmp, ENV_FILE);
  for (const [k, v] of Object.entries(values)) process.env[k] = v;
}

export const config = {
  get nodeEnv() { return process.env.NODE_ENV ?? 'production'; },
  get isProd() { return (process.env.NODE_ENV ?? 'production') === 'production'; },
  get port() { return Number(process.env.PORT ?? 3000); },
  get host() { return process.env.HOST ?? '0.0.0.0'; },
  get appSecret() { return process.env.APP_SECRET ?? ''; },
  get encryptionKey() { return process.env.ENCRYPTION_KEY ?? ''; },
  get redisUrl() { return process.env.REDIS_URL ?? ''; },
  get trustProxy() { return process.env.TRUST_PROXY ?? '1'; },
  get installToken() { return process.env.INSTALL_TOKEN ?? ''; },
  get db() {
    return {
      host: process.env.DB_HOST ?? '',
      port: Number(process.env.DB_PORT ?? 3306),
      user: process.env.DB_USER ?? '',
      password: process.env.DB_PASSWORD ?? '',
      database: process.env.DB_NAME ?? '',
    };
  },
  get dbConfigured() { return Boolean(process.env.DB_HOST && process.env.DB_NAME && process.env.DB_USER); },
};
