import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Directory layout
 *
 *   <shared>/            ← SHOPIGO_SHARED or the application root
 *     .env               ← generated by the installer (never inside a release)
 *     storage/           ← install.lock, backups, logs, update staging, cache
 *     uploads/           ← customer-visible media (optimised images)
 *     releases/<ver>/    ← versioned application code installed by the updater
 *
 * The code itself (server/dist, client/dist) lives either directly in the
 * application root (first install) or inside releases/<version>/. Shared data
 * is always resolved against the shared root so updates never touch it.
 */
const here = path.dirname(fileURLToPath(import.meta.url));
// server/dist/core or server/src/core → app root is three levels up
export const APP_ROOT = path.resolve(here, '..', '..', '..');

function detectSharedRoot(): string {
  if (process.env.SHOPIGO_SHARED) return path.resolve(process.env.SHOPIGO_SHARED);
  const parent = path.dirname(APP_ROOT);
  if (path.basename(parent) === 'releases') return path.dirname(parent);
  return APP_ROOT;
}

export const SHARED_ROOT = detectSharedRoot();
export const ENV_FILE = path.join(SHARED_ROOT, '.env');
export const STORAGE_DIR = path.join(SHARED_ROOT, 'storage');
export const UPLOADS_DIR = path.join(SHARED_ROOT, 'uploads');
export const RELEASES_DIR = path.join(SHARED_ROOT, 'releases');
export const INSTALL_LOCK = path.join(STORAGE_DIR, 'install.lock');
export const MAINTENANCE_FILE = path.join(STORAGE_DIR, 'maintenance.json');
export const BACKUP_DIR = path.join(STORAGE_DIR, 'backups');
export const LOG_DIR = path.join(STORAGE_DIR, 'logs');
export const UPDATE_STAGING_DIR = path.join(STORAGE_DIR, 'updates');
export const CURRENT_RELEASE_FILE = path.join(STORAGE_DIR, 'current-release');
export const CLIENT_DIST = path.join(APP_ROOT, 'client', 'dist');
export const SERVER_DATA_DIR = path.join(APP_ROOT, 'server', 'dist', 'data');

export const STORAGE_SUBDIRS = [STORAGE_DIR, BACKUP_DIR, LOG_DIR, UPDATE_STAGING_DIR, path.join(STORAGE_DIR, 'cache'), path.join(STORAGE_DIR, 'tmp')];
export const UPLOAD_SUBDIRS = ['products', 'banners', 'branding', 'categories', 'brands', 'combos', 'media'].map((d) => path.join(UPLOADS_DIR, d));

export function ensureDirs(): void {
  for (const dir of [...STORAGE_SUBDIRS, UPLOADS_DIR, ...UPLOAD_SUBDIRS]) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

/** Resolve a user-influenced relative path inside a base directory, refusing traversal. */
export function safeJoin(base: string, relative: string): string {
  const target = path.resolve(base, relative);
  const rel = path.relative(base, target);
  if (rel.startsWith('..') || path.isAbsolute(rel)) {
    throw new Error('Path traversal rejected');
  }
  return target;
}
